DROP TABLE IF EXISTS user;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    blitz TEXT NOT NULL,
    rapid TEXT NOT NULL,
    puzzle TEXT NOT NULL,
    created TEXT NOT NULL,
    playTime INTEGER NOT NULL,
);
